package com.example.admin.newsnews.tool;

import com.example.admin.newsnews.bean.NewsClassify;

import java.util.ArrayList;

/**
 * Created by Adamlambert on 2016/10/19.
 */
public class Constans {
    public static ArrayList<NewsClassify> getData()
    {
        ArrayList<NewsClassify> newsClassifies = new ArrayList<>();
        NewsClassify classify = new NewsClassify();
        classify.setId(0);
        classify.setTitle("头条");
        classify.setUrlId(Url.TopId);
        newsClassifies.add(classify);
        classify = new NewsClassify();
        classify.setId(1);
        classify.setUrlId(Url.DianYingId);
        classify.setTitle("电影");
        newsClassifies.add(classify);
        classify = new NewsClassify();
        classify.setId(2);
        classify.setTitle("游戏");
        classify.setUrlId(Url.YouXiId);
        newsClassifies.add(classify);
        classify = new NewsClassify();
        classify.setId(3);
        classify.setTitle("社会");
        classify.setUrlId(Url.SheHuiId);
        newsClassifies.add(classify);
        classify = new NewsClassify();
        classify.setId(4);
        classify.setTitle("笑话");
        classify.setUrlId(Url.XiaoHuaId);
        newsClassifies.add(classify);
        classify = new NewsClassify();
        classify.setId(5);
        classify.setUrlId(Url.CaiJingId);
        classify.setTitle("财经");
        newsClassifies.add(classify);
        classify = new NewsClassify();
        classify.setId(6);
        classify.setUrlId(Url.KeJiId);
        classify.setTitle("科技");
        newsClassifies.add(classify);
        classify = new NewsClassify();
        classify.setId(7);
        classify.setUrlId(Url.JunShiId);
        classify.setTitle("军事");
        newsClassifies.add(classify);
        return newsClassifies;
    }
    public static ArrayList<NewsClassify> removeData(){
        ArrayList<NewsClassify> newsClassifies = new ArrayList<>();
        NewsClassify classify = new NewsClassify();
        classify.setId(0);
        classify.setTitle("推荐");
        classify.setUrlId(Url.JingXuanId);
        newsClassifies.add(classify);
        classify = new NewsClassify();
        classify.setId(1);
        classify.setTitle("电影");
        classify.setUrlId(Url.DianYingId);
        newsClassifies.add(classify);
        classify = new NewsClassify();
        classify.setId(2);
        classify.setTitle("财经");
        classify.setUrlId(Url.CaiJingId);
        newsClassifies.add(classify);
        classify = new NewsClassify();
        classify.setId(3);
        classify.setTitle("头条");
        classify.setUrlId(Url.TopId);
        newsClassifies.add(classify);
        classify = new NewsClassify();
        classify.setId(4);
        classify.setTitle("社会");
        classify.setUrlId(Url.SheHuiId);
        newsClassifies.add(classify);
        classify = new NewsClassify();
        classify.setId(5);
        classify.setTitle("娱乐");
        classify.setUrlId(Url.YuLeId);
        newsClassifies.add(classify);
        classify = new NewsClassify();
        classify.setId(6);
        classify.setTitle("科技");
        classify.setUrlId(Url.KeJiId);
        newsClassifies.add(classify);
        classify = new NewsClassify();
        classify.setId(7);
        classify.setTitle("汽车");
        classify.setUrlId(Url.QiChiId);
        newsClassifies.add(classify);
        classify = new NewsClassify();
        classify.setId(8);
        classify.setTitle("足球");
        classify.setUrlId(Url.FootId);
        newsClassifies.add(classify);
        classify = new NewsClassify();
        classify.setId(9);
        classify.setTitle("体育");
        classify.setUrlId(Url.TiYuId);
        newsClassifies.add(classify);
        classify = new NewsClassify();
        classify.setId(10);
        classify.setTitle("笑话");
        classify.setUrlId(Url.XiaoHuaId);
        newsClassifies.add(classify);
        classify = new NewsClassify();
        classify.setId(11);
        classify.setTitle("游戏");
        classify.setUrlId(Url.YouXiId);
        newsClassifies.add(classify);
        classify = new NewsClassify();
        classify.setId(12);
        classify.setTitle("时尚");
        classify.setUrlId(Url.ShiShangId);
        newsClassifies.add(classify);
        classify = new NewsClassify();
        classify.setId(13);
        classify.setTitle("情感");
        classify.setUrlId(Url.QingGanId);
        newsClassifies.add(classify);
        classify = new NewsClassify();
        classify.setId(14);
        classify.setTitle("电台");
        classify.setUrlId(Url.DianTaiId);
        newsClassifies.add(classify);
        classify = new NewsClassify();
        classify.setId(15);
        classify.setTitle("NBA");
        classify.setUrlId(Url.NBAId);
        newsClassifies.add(classify);
        classify = new NewsClassify();
        classify.setId(16);
        classify.setTitle("彩票");
        classify.setUrlId(Url.CaiPiaoId);
        newsClassifies.add(classify);
        classify = new NewsClassify();
        classify.setId(17);
        classify.setTitle("数码");
        classify.setUrlId(Url.ShuMaId);
        newsClassifies.add(classify);
        classify = new NewsClassify();
        classify.setId(18);
        classify.setTitle("移动");
        classify.setUrlId(Url.YiDongId);
        newsClassifies.add(classify);
        classify = new NewsClassify();
        classify.setId(19);
        classify.setTitle("教育");
        classify.setUrlId(Url.JiaoYuId);
        newsClassifies.add(classify);
        classify = new NewsClassify();
        classify.setId(20);
        classify.setTitle("论坛");
        classify.setUrlId(Url.LunTanId);
        newsClassifies.add(classify);
        classify = new NewsClassify();
        classify.setId(21);
        classify.setTitle("旅游");
        classify.setUrlId(Url.LvYouId);
        newsClassifies.add(classify);
        classify = new NewsClassify();
        classify.setId(22);
        classify.setTitle("手机");
        classify.setUrlId(Url.ShouJiId);
        newsClassifies.add(classify);
        classify = new NewsClassify();
        classify.setId(23);
        classify.setTitle("博客");
        classify.setUrlId(Url.BoKeId);
        newsClassifies.add(classify);
        classify = new NewsClassify();
        classify.setId(24);
        classify.setTitle("家具");
        classify.setUrlId(Url.JiaJuId);
        newsClassifies.add(classify);
        classify = new NewsClassify();
        classify.setId(25);
        classify.setTitle("亲子");
        classify.setUrlId(Url.QinZiId);
        newsClassifies.add(classify);
        classify = new NewsClassify();
        classify.setId(26);
        classify.setTitle("暴雪");
        classify.setUrlId(Url.BaoXueId);
        newsClassifies.add(classify);
        classify = new NewsClassify();
        classify.setId(27);
        classify.setTitle("CBA");
        classify.setUrlId(Url.CBAId);
        newsClassifies.add(classify);
        classify = new NewsClassify();
        classify.setId(28);
        classify.setTitle("消息");
        classify.setUrlId(Url.MsgId);
        newsClassifies.add(classify);
        classify = new NewsClassify();
        classify.setId(29);
        classify.setTitle("军事");
        classify.setUrlId(Url.JunShiId);
        newsClassifies.add(classify);

        return newsClassifies;
    }
}
